version: "3.8"
services:
  redc_backend:
    container_name: redc_backend
    image: nashvador/redc-backend:latest
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=redc_database
      - PGHOST=redc_db 
    depends_on:
      - redc_db
    volumes:
      - ./:/usr/src/app
  redc_db:
    container_name: redc_db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=redc_database
    volumes:
      - nps_data:/var/lib/postgresql/data
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"  
  #   restart: always
  #   ports:
  #     - "5050:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: 12345
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin

volumes:
  nps_data: {}
  # pgadmin-data: {}