version: "3.8"
services:
  redc_backend:
    container_name: redc_backend
    image: nashvador/redc-backend:latest
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=redc_database
      - PGHOST=redc_db 
    depends_on:
      - redc_db
    volumes:
      - ./:/usr/src/app
  redc_db:
    container_name: redc_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=redc_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}